Repository OpenUserJS/OpenUserJS.org, pull requests merged in 2019-04, with the labels that each got.

#1601 Spdx update
  libs/blockSPDX.json
  libs/helpers.js
  package.json
Labels: CODE, bug, migration

#1602 Some dep updates
  package.json
Labels: CODE, migration, security

#1603 Migrate to *node*@12.0.0
  app.js
  package.json
Labels: CODE, migration, security

#1604 Update LICENSE
  LICENSE
Labels: DOC, PR READY, enhancement
